services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: si_user
      POSTGRES_PASSWORD: si_password
      POSTGRES_DB: si_calibrator
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
